DUNE_CLIENT_API = 'F305q6b4s9NO5T3GykbcM4xPnviEDPGy'
DUNE_CLIENT = '8nKfTWcJtcVteAAF01yRNlpi7EW1C70M'
GECKO_API_KEY = 'CG-nm5ynnbGBWTugQhVY2vNMWbP'
MORALIS_API_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJub25jZSI6IjdlMjBjNDk0LWU0MjAtNGFmOC05MzM2LTkxNTBjNDU3MmJjZCIsIm9yZ0lkIjoiNDY4ODE1IiwidXNlcklkIjoiNDgyMjkyIiwidHlwZUlkIjoiMDk3MTE4YTItNWVkOC00Yjc2LTg5YWItMjM5NDgzNDVjYzNiIiwidHlwZSI6IlBST0pFQ1QiLCJpYXQiOjE3NTY4NDM1NjIsImV4cCI6NDkxMjYwMzU2Mn0.yLn2ojeo6b4qJA9IYnSJlel5gZVlJChuZbhqkUBSLeo'
